#! /bin/sh -e
if [ "$1" = "configure" ]; then
	for i in ipython pycolor ; do
    	update-alternatives \
			--install /usr/bin/$i $i /usr/bin/python2.4-$i 30 \
			--slave /usr/share/man/man1/$i.1.gz $i.1.gz /usr/share/man/man1/python2.4-$i.1.gz
	done
	update-alternatives --remove irunner /usr/bin/python2.4-irunner
	update-alternatives --install /usr/bin/irunner irunner /usr/bin/python2.4-irunner 30
fi

#DEBHELPER#
